-- ─────────────────────────────────────────────
-- SEED SCRIPT — Run AFTER setting up postgres_fdw
-- or manually export/import from Lovable Supabase
--
-- Option A (manual): Export ticker_search from
-- Lovable Supabase SQL Editor as CSV, then import
-- here via Supabase Table Editor → Import CSV
--
-- Option B (direct insert via enrichment agent):
-- The ticker-enrichment-agent reads from the source
-- Supabase using HF_SOURCE_SUPABASE_URL env var and
-- populates seo_tickers automatically in batches.
--
-- This file documents the expected column mapping:
-- source: ticker_search.symbol → seo_tickers.ticker
-- source: ticker_search.name   → seo_tickers.company_name
-- source: ticker_search.type   → seo_tickers.type (normalize: CS=stock, ETF=etf)
-- source: ticker_search.primary_exchange → seo_tickers.exchange
-- source: ticker_search.market_cap → seo_tickers.market_cap
-- ─────────────────────────────────────────────

-- Placeholder — actual seed runs via enrichment agent
SELECT 'Run ticker-enrichment-agent to populate seo_tickers from source Supabase' as note;
